title: Live A Hero Wiki
url: https://liveahero-wiki.github.io
github_edit: https://github.com/liveahero-wiki/liveahero-wiki.github.io/edit/master
permalink: /news/:year/:month/:title/
timezone: Asia/Tokyo
date_format: "%-d %b %Y %R JST"
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
  style: compressed
plugins:
  #- jekyll-feed
  - jekyll-redirect-from
  #- jekyll-sitemap
  - jemoji
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "charas"
    values:
      unreleased: false
      additional_scripts: ["/assets/atlas.min.js"]
  - scope:
      type: "events"
    values:
      layout: event
  - scope:
      type: "main_quests"
    values:
      layout: main_quest
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "google9c8bdece57d6fa9c.html"
    values:
      sitemap: false

collections:
  charas:
    output: true
  events:
    output: true
    sort_by: event_start_time
  main_quests:
    output: true
    sort_by: chapterId

exclude:
  - "*.py"
  - "assets/atlas.js"
  - readme.md
  - CONTRIBUTING.md