title: Live A Hero Wiki
url: https://liveahero-wiki.github.io
github_edit: https://github.com/liveahero-wiki/liveahero-wiki.github.io/edit/master
permalink: /news/:year/:month/:title/
markdown: kramdown
#kramdown:
#  parse_block_html: true
sass:
  style: compressed
plugins:
  #- jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "charas"
    values:
      unreleased: false
  - scope:
      path: "assets/img/fg"
    values:
      fg: true
  - scope:
      path: "assets"
    values:
      sitemap: false

collections:
  charas:
    output: true
